config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  root to:"diaries#top"
  get "/index", to:"diaries#index"
  get "/new", to:"diaries#new"
  post "/create", to:"diaries#create"
  delete "/diaries/:id", to:"diaries#destroy"
  get "/diaries/:id/edit", to:"diaries#edit"
  patch "/diaries/:id", to:"diaries#update"
  get "/diaries/:id", to:"diaries#show"

  get '/signup', to: 'users#new'
  resources :users
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
    validates :place, :someone, :action, presence: true
    default_scope -> { order(created_at: :desc) }
    #belongs_to :user,optional: true 
    #validates :user_id, presence: true #ここの二行のコメントアウトを外すと投稿できなくなる
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } #case_sensitiveは大文字小文字を区別せずに一意性を検証してくれる
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
   has_many :diaries, dependent: :destroy

    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # 永続セッションのためにユーザーをデータベースに記憶する
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # 渡されたトークンがダイジェストと一致したらtrueを返す
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
  
    # ユーザーのログイン情報を破棄する
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
 
  def index
      @diaries = Diary.all
  end

  def create
      if Diary.create(place: params["diary"]["place"], someone: params["diary"]["someone"], action: params["diary"]["action"]).valid?
          flash[:success] = "Created!"
          redirect_to "/index"
      else
          flash[:danger] = "Error!全部入力してね"
          redirect_to "/new"
      end
  end
  
  def new
  end
  
  def top
  end
  
  def destroy
      diary = Diary.find(params["id"])
      diary.destroy
      flash[:success] = "Deleted!"
      redirect_to "/index"
  end

  def edit
      @diary = Diary.find(params["id"])
  end
  
  def update
      diary = Diary.find(params["id"])
      diary.place = params["diary"]["place"]
      diary.someone = params["diary"]["someone"]
      diary.action = params["diary"]["action"]
      diary.save
      flash[:success] = "Updated!"
      redirect_to "/index"
  end
  
  def show
      @diary = Diary.find(params["id"])
      #@user = User.find(params["id"])
      #user.name = params["user"]["name"]
      #@user = User.find(params["id"])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = "Login to One line diary!"
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
   before_action :correct_user,   only: [:edit, :update]
   before_action :admin_user,     only: :destroy

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params) 
    if @user.save
      log_in @user
      flash[:success] = "Welcome to One line diary!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
    
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
    
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
                                                    # ユーザーのセッションを永続的にする
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
    # 渡されたユーザーがログイン済みユーザーであればtrueを返す
    def current_user?(user)
        user == current_user
    end


    def current_user                            # 現在ログインしているユーザーを返す (いる場合)
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
                elsif (user_id = cookies.signed[:user_id])
                    user = User.find_by(id: user_id)
                        if user && user.authenticated?(cookies[:remember_token])
                        log_in user
                        @current_user = user
                        end
        end
    end

    def logged_in?                              # ユーザーがログインしていればtrue、その他ならfalseを返す
        !current_user.nil?
    end
    
    # 永続的セッションを破棄する
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

  # 現在のユーザーをログアウトする
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    # 記憶したURL (もしくはデフォルト値) にリダイレクト
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    # アクセスしようとしたURLを覚えておく
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/edit.html.erb
<h1><span class="red">E</span>dit page</h1>

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js"></script><!-- moment.jsを使って日本語対応 -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>
    
    <script>
      $(function(){
      $("#picker").bootstrapMaterialDatePicker({
      weekStart:0,
      lang:"ja",
      time:false,
      format:"YYYY-MM-DD HH:mm"
      });
      });
    </script>
  </head>
  <body>
    <div class="well well" >
      <%= form_tag("/diaries/"+@diary.id.to_s,:method=>:patch) do %>
      <%= text_field :diary, :place %>
      <%= text_field :diary, :someone %>
      <%= text_field :diary, :action %>
      <input type="text" id="picker" placeholder="執筆日">
      <%= button_tag "作成",class: "btn btn-primary"  %>
     <% end %>
    </div>
  </body>
</html>

app/views/diaries/index.html.erb
<h1><span class="red">H</span>istory</h1>
  <table class="table table">
    <% @diaries.each do |diary| %>
      <div class="well well" ><span class="content"><%= diary.place%> <%= diary.someone%> <%= diary.action%> / <%= diary.created_at%></span>
        <div class="buttons">
          <%= link_to '詳細', "/diaries/#{diary.id}", method: :get %>
          <span class="trash"><a href="/diaries/<%=diary.id %>" data-method="delete"><span class="glyphicon glyphicon-trash"></span></a></span>
          <a href="/diaries/<%=diary.id %>/edit"><span class="glyphicon glyphicon-edit"></span></a>
          <span class="twitter"><a href="https://twitter.com/share" class="twitter-share-button" data-url="" data-text="<%= diary.place%><%= diary.someone%><%= diary.action%> #onelinediary">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></span>
        </div>
      </div>  
    <% end %>
  </table>

app/views/diaries/new.html.erb
<h1><span class="red">N</span>ew diary</h1>

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js"></script><!-- moment.jsを使って日本語対応 -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>
    
    <script>
      $(function(){
      $("#picker").bootstrapMaterialDatePicker({
      weekStart:0,
      lang:"ja",
      time:false,
      format:"YYYY-MM-DD HH:mm"
      });
      });
    </script>
  </head>
  <body>
   <div class="well well" >
    <%= form_tag("/create") do %>
    <%= text_field :diary, :place ,placeholder:"どこで"%>
    <%= text_field :diary, :someone ,placeholder:"誰と"%>
    <%= text_field :diary, :action ,placeholder:"何をした"%>
    <input type="text" id="picker" placeholder="執筆日">
    <%= button_tag "作成",class: "btn btn-primary" %>
    <% end %>
   </div>
  </body>
</html>

app/views/diaries/show.html.erb
<h1><span class="red">D</span>etail</h1>
  <table class="table table">
      <div class="well well" ><span class="content"><%= @diary.place%> <%= @diary.someone%> <%= @diary.action%> / <%= @diary.created_at%></span>
        <div class="buttons">
          <span class="trash"><a href="/diaries/<%=@diary.id %>" data-method="delete"><span class="glyphicon glyphicon-trash"></span></a></span>
          <a href="/diaries/<%=@diary.id %>/edit"><span class="glyphicon glyphicon-edit"></span></a>
          <span class="twitter"><a href="https://twitter.com/share" class="twitter-share-button" data-url="" data-text="<%= @diary.place%><%= @diary.someone%><%= @diary.action%> #onelinediary">Tweet</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></span>
        </div>
      </div>  
  </table>

app/views/diaries/top.html.erb
<div class="jumbotron">
  <h1><span class="red">O</span>ne Line Diary</h1>
  <p>Just 3 words you need</p>
  <span><a class="btn btn-primary btn-lg" href="/new" role="button">Write</a></span>
  <span><a class="btn btn-warning btn-lg" href="/login" role="button">Login</a></span>
  <span><%= link_to "Sign up", signup_path, class: "btn btn-success btn-lg" %></span>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />

  <head>
    <title>OneLineDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            
            <a class="navbar-brand" href="/">Top</a>
            <a class="navbar-brand" href="/index">History</a>
            <a class="navbar-brand" href="/new">New diary</a>
            
            
              <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                  <li><%= link_to "Users", users_path %></li>
                  <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                  </ul>
                  </li>
                  <% else %>
                  <li><%= link_to "Log in", login_path %></li>
                <% end %>
              </ul>
            
            
            
          </div>
        </div><!-- /.container-fluid -->
      </nav>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    / <span class= "btn btn-success"><%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %></sapn>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class="jumbotron">
  <% provide(:title, "Edit user") %>
  <h1><span class="red">U</span>pdate your profile</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
  
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
  
        <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
  <% provide(:title, 'All users') %>
<h1><span class="red">A</span>ll accout</h1>
  <table class="table table">
    <% @user.each do |user| %>
      <div class="well well" ><span class="content"><%= link_to render user %></span></div>  
    <% end %>
  </table>

app/views/users/new.html.erb
<div class="jumbotron">
  <h1><span class="red">S</span>ign up now</h1>

    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: signup_path) do |f| %>
        <%= render 'shared/error_messages' %>
        
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
    
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
    
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
    
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
    
          <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
        
      </div>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>